name: Deploy Python API to EC2

on:
  push:
    branches:
      - main   # Trigger deployment on push to the main branch
  pull_request:
    branches:
      - main   # Trigger deployment on pull request to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'  # Specify the Python version


      # Add EC2 SSH private key to GitHub Actions environment
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      # Set up known_hosts to avoid SSH warning
      - name: Add EC2 to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Deploy to EC2
      - name: Deploy to EC2
        run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /var/www/flask-app  # Change to the directory where your app is located
            git pull origin main  # Pull the latest changes from GitHub
            source venv/bin/activate  # Activate virtual environment if using one
            # Restart your app (for example, using Gunicorn or another service manager)
            sudo systemctl restart flask.service  # Adjust based on your service name
          EOF

